### ISSUE TITLE
Add `xontrib` and `xonsh` topics to the repo about settings

### ISSUE THREAD

**Issue by anki-code** [xonsh/xontrib-ptk-shell#1]
Thanks!

**Comment by jnoortheen** [comment]
@gforsyth could you check this https://github.com/xonsh/xontrib-ptk-shell#xontrib-promotion-read-and-remove-this-section ?
having a PYPI token would help publish on new releases

**Comment by jnoortheen** [comment]
@gforsyth I think this repo can be archived or deleted. I will create a sub-package for ptk-shell inside the xonsh as mono-repo https://github.com/xonsh/xonsh/pull/4862#issuecomment-1184639183
